package org.acme.insurance.policyquote;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Policy implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "POLICY_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "POLICY_ID_GENERATOR", sequenceName = "POLICY_ID_SEQ")
    private java.lang.Long id;

    public Policy() {
    }
    
    public Policy(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}