//created on: 09-Jun-2016
package org.acme.insurance.policyquote

//list any import classes here.
import org.acme.insurance.Driver
import org.acme.insurance.Policy


//declare any global variables here


rule "SafeYouths"

    when
        //conditions
        driver : Driver(age >= 18 && < 25, numberOfAccidents < 1, numberOfTickets <=1)
        policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(450)};
        System.out.println("fire fule "  + kcontext.getRule().getName());
   

end

